apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-hello-nestjs.fullname" . }}
  labels:
    {{- include "sample-hello-nestjs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-hello-nestjs.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-hello-nestjs.labels" . | nindent 8 }}
    spec:
      containers:
        - name: sample-hello-nestjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
