k3s_role: server # server | agent
k3s_version: "" # 비워두면 최신 stable
k3s_extra_exec_args: ""
k3s_server_url: "" # k3s_role == agent 일 때 필수 (예: https://10.0.1.10:6443)
k3s_token: "" # k3s_role == agent 일 때 필수
k3s_kubeconfig_fetch_dir: "{{ playbook_dir }}/../fetched"
